# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - main # Assuming 'main' is your default branch
      - feature/refactor-ux-perf # Deploy the feature branch as well
  workflow_dispatch:

permissions:
  contents: write # Needs write to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Determine Base URL and Destination Directory
        id: path_config
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "VITE_BASE_URL=/mvb/" >> $GITHUB_ENV
            echo "DEST_DIR=." >> $GITHUB_ENV
            echo "Deployed URL: https://${{ github.repository_owner }}.github.io/mvb/"
          elif [ "${{ github.ref_name }}" == "feature/refactor-ux-perf" ]; then
            echo "VITE_BASE_URL=/mvb/beta/" >> $GITHUB_ENV
            echo "DEST_DIR=beta" >> $GITHUB_ENV
            echo "Deployed URL: https://${{ github.repository_owner }}.github.io/mvb/beta/"
          else
            echo "Branch not configured for deployment. Exiting."
            exit 1
          fi

      - name: Build
        run: npm run build
        env:
          VITE_BASE_URL: ${{ env.VITE_BASE_URL }} # Use the base URL determined in the previous step

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages # Branch to deploy to
          publish_dir: ./dist   # Directory to deploy
          destination_dir: ${{ env.DEST_DIR }} # Deploy to root or subfolder
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploying ${{ github.ref_name }} to ${{ env.DEST_DIR }}
          keep_files: ${{ github.ref_name != 'main' }} # Keep files for feature branches, main branch overwrites
          allow_empty_commit: true
